import os
import re
import sys
from pyspark.sql.types import StringType, StructField, StructType
from pyspark.sql.functions import col, trim, lit, monotonically_increasing_id, coalesce, current_timestamp, udf
from awsglue import DynamicFrame
from awsglue.dynamicframe import DynamicFrameCollection
from pyspark.sql.utils import AnalysisException
from datetime import datetime

# Import our modularized files
from CustomErrorLibs import raise_custom_error
from CustomDbConnLibs import get_postgres_jdbc_conf, execute_postgres_query
from Utils import generate_uuidv7

# Register the imported generator as a PySpark UDF
uuidv7_udf = udf(generate_uuidv7, StringType())


# ===============================================================================
# --- HELPER FUNCTIONS & FUZZY MATCHING LOGIC ---
# ===============================================================================
def norm(val):
    if val is None:
        return ""
    
    val_str = str(val).strip()

    if val_str.lower() == "none" or not val_str:
        return ""
    
    return re.sub(r'\s+', ' ', val_str).strip()

def clean_col_name(name):
    return name

def optimized_header_match(sample_rows, target_headers, num_cols):
    best_mapping = {}
    best_count = 0
    header_end_index = -1
    
    for start_r in range(min(15, len(sample_rows))):
        for window_size in range(1, 10):
            end_r = start_r + window_size
            if end_r > len(sample_rows):
                break
            
            col_strs = {}
            for c in range(num_cols):
                col_parts = [norm(sample_rows[r][c]) for r in range(start_r, end_r)]
                combined = norm(" ".join([p for p in col_parts if p]))
                if combined:
                    col_strs[c] = combined
            
            scores = []
            for c, c_str in col_strs.items():
                for th in target_headers:
                    c_clean = c_str.lower().replace(" ", "").replace("-", "")
                    th_clean = th.lower().replace(" ", "").replace("-", "")
                    
                    if c_clean == th_clean:
                        score = 1.0
                    elif th_clean in c_clean or c_clean in th_clean:
                        score = 0.8
                    elif len(set(c_clean) & set(th_clean)) >= 3:
                        score = 0.7
                    else:
                        score = 0.0
                    
                    if score >= 0.7:
                        scores.append((score, c, th))
            
            scores.sort(key=lambda x: x[0], reverse=True)
            current_mapping = {}
            used_cols = set()
            used_targets = set()
            
            for score, c, th in scores:
                if c not in used_cols and th not in used_targets:
                    current_mapping[c] = th
                    used_cols.add(c)
                    used_targets.add(th)
            
            if len(current_mapping) > best_count:
                best_count = len(current_mapping)
                header_end_index = end_r - 1
                best_mapping = current_mapping
    
    return best_mapping, header_end_index, best_count


# ===============================================================================
# --- SPARK-NATIVE DATA TRANSFORM (HEADED MODE) ---
# ===============================================================================
def MyTransform(glueContext, dfc, target_headers_list) -> DynamicFrameCollection:
    target_headers = [norm(h) for h in target_headers_list if norm(h)]
    
    input_df_name = list(dfc.keys())[0]
    input_dyf = dfc.select(input_df_name)
    spark_df = input_dyf.toDF()
    
    data_cols = [c for c in spark_df.columns if c != "_temp_row_num"]
    num_cols = len(data_cols)
    
    sample_df = spark_df.limit(50)
    all_rows = sample_df.collect()

    col_mapping, header_end_index, best_match_count = optimized_header_match(all_rows, target_headers, num_cols)
    print(f"### -Universal Fuzzy Detector matched {best_match_count}/{len(target_headers)} headers ending at row index {header_end_index}.")

    if header_end_index >= 0 and col_mapping:
        data_start_index = header_end_index + 1
        sorted_cols = sorted(col_mapping.keys())
        
        data_df = spark_df.rdd.zipWithIndex().filter(
            lambda row_with_index: row_with_index[1] >= data_start_index
        ).map(lambda row_with_index: row_with_index[0])
        
        data_df = glueContext.spark_session.createDataFrame(data_df, spark_df.schema)
        
        footer_keywords = ['report creator', 'page ', 'run time', 'generated by', 'end of report', 'confidential', 'rows selected']
        footer_pattern = "(?i)(" + "|".join(footer_keywords) + ")"
        
        footer_condition = lit(False)
        non_empty_condition = lit(False)
        
        for c in range(num_cols):
            col_name = data_df.columns[c]
            safe_col = coalesce(col(col_name).cast("string"), lit(""))
            
            footer_condition = footer_condition | safe_col.rlike(footer_pattern)
            non_empty_condition = non_empty_condition | (safe_col != "")
        
        filtered_data_df = data_df.filter(non_empty_condition & ~footer_condition)
        
        selected_columns = []
        for c in sorted_cols:
            original_col_name = data_df.columns[c]
            target_col_name = clean_col_name(col_mapping[c])
            selected_columns.append(trim(col(original_col_name)).alias(target_col_name))
        
        selected_columns.append(col("_temp_row_num"))
        final_df = filtered_data_df.select(*selected_columns)
            
    else:
        schema = StructType([StructField("No_Data_Found", StringType(), True)])
        final_df = glueContext.spark_session.createDataFrame([["No valid data range found"]], schema)

    result_dyf = DynamicFrame.fromDF(final_df, glueContext, "extracted_data")
    return DynamicFrameCollection({"CustomTransform0": result_dyf}, glueContext)


# ===============================================================================
# --- MAIN PIPELINE EXECUTION ---
# ===============================================================================
def execute_pipeline(args, spark, glueContext):
    
    def get_text_arg(name, default_val):
        for i, val in enumerate(sys.argv):
            if val == f"--{name}" and len(sys.argv) > i + 1:
                return sys.argv[i + 1]
        return default_val

    target_headers_raw = args.get('target_headers', '')
    row_number_label = args.get('row_number_label', '')
    input_file_name = args['input_file_name']
    input_path = args['input_file_path'] + input_file_name
    connection_name = args['connection_name']
    xform_ctx_jobname = args['JOB_NAME']
    target_raw = args['target_table']
    audit_target_raw = get_text_arg('audit_table', None)
    
    # ---------------------------------------------------------
    #   DERIVE BILL CYCLE & FILENAME
    # ---------------------------------------------------------
    file_name_no_ext = os.path.splitext(input_file_name)[0]
    billcycle_val = "BC"+file_name_no_ext[-2:]

    print(f"### -Reading Excel file: {input_path} at {datetime.now()}")
    
    # ===============================================================================
    # --- READ AND EXPAND DATA ---
    # ===============================================================================
    try:
        spark_df = (
            spark.read.format("com.crealytics.spark.excel")
            .option("header", "false")
            .option("inferSchema", "false")
            .option("treatEmptyValuesAsNulls", "false")
            .option("dataAddress", "A1")
            .option("useHeaderRowIndex", "false")
            .load(input_path)
        )

    except AnalysisException as e:
        if "Path does not exist" in str(e):
            raise_custom_error("missing_file", "S3 object not found or access denied", input_path)
        else:
            raise e
            
    # STAMP ORIGINAL ORDER STRICTLY (1, 2, 3...)
    from pyspark.sql.window import Window
    from pyspark.sql.functions import row_number, lit
    window_spec = Window.orderBy(lit(1))
    spark_df = spark_df.withColumn("_temp_row_num", row_number().over(window_spec))
        
    # INGESTION TYPE ROUTER (FLAT or HEADED path)
    if target_headers_raw:
        print(f"### -Target headers detected. Routing to HEADED mode...")
        raw_headers_list = target_headers_raw.split(",")
        s3_dyf = DynamicFrame.fromDF(spark_df, glueContext, "s3_dyf")
        transform_collection = MyTransform(glueContext, DynamicFrameCollection({"s3_dyf": s3_dyf}, glueContext), raw_headers_list)
        
        from awsglue.transforms import SelectFromCollection
        transformed_dyf = SelectFromCollection.apply(
            dfc=transform_collection, 
            key=list(transform_collection.keys())[0], 
            transformation_ctx="xformed_dyf-" + xform_ctx_jobname
        )
        final_df = transformed_dyf.toDF()

        row_count = final_df.count()
        if row_count == 0 or "No_Data_Found" in final_df.columns:
            print("### -Fuzzy matcher failed or sheet is blank")
            raise_custom_error("empty_data", "Fuzzy matcher failed or sheet is blank", input_path)

    else:
        print("### -No target headers detected. Routing to FLAT sequential mode...")
        data_columns = [c for c in spark_df.columns if c != "_temp_row_num"]
        new_column_names = [f"column{i+1}" for i in range(len(data_columns))]

        mapping_exprs = [col(old_name).alias(new_name) for old_name, new_name in zip(data_columns, new_column_names)]
        mapping_exprs.append(col("_temp_row_num")) 
        final_df = spark_df.select(*mapping_exprs)

    # STRICT ORDERING
    # Retain _temp_row_num here so the Audit table can use it
    final_df = (
        final_df.coalesce(1)
        .orderBy(col("_temp_row_num").asc())
    )

    # Cache the DataFrame because of writing to 2 different tables
    final_df.cache()

    # ===============================================================================
    # --- CONNECTION SETUP ---
    # ===============================================================================
    jdbc_url, connection_properties = get_postgres_jdbc_conf(glueContext, connection_name)

    def quote_table(raw_name):
        if "." in raw_name:
            schema_part, table_part = raw_name.split(".", 1)
            return f'"{schema_part}"."{table_part}"'
        return f'"{raw_name}"'

    quoted_target_table = quote_table(target_raw)

    # ===============================================================================
    # --- DBWRITE 1: MAIN DATA TABLE ---
    # ===============================================================================
    print(f"### -Preparing primary write to {quoted_target_table}...")
    
    # Drop the temp row num only for the 1st table's write process
    main_write_df = final_df.drop("_temp_row_num")

    try:
        target_schema_df = spark.read.jdbc(
            url=jdbc_url,
            table=quoted_target_table,
            properties=connection_properties
        )
        target_columns = target_schema_df.columns
        final_columns_lower = [c.lower() for c in main_write_df.columns]
        
        skip_label = row_number_label.lower() if row_number_label else None
        
        for t_col in target_columns:
            if skip_label and t_col.lower() == skip_label:
                continue
            if t_col.lower() not in final_columns_lower:
                main_write_df = main_write_df.withColumn(t_col, lit(None).cast("string"))
        
        columns_to_select = []
        for t_col in target_columns:
            if skip_label and t_col.lower() == skip_label:
                continue
            matched_col = next((c for c in main_write_df.columns if c.lower() == t_col.lower()), t_col)
            columns_to_select.append(col(matched_col).alias(t_col))
                
        main_write_df = main_write_df.select(*columns_to_select)
        
    except Exception as e:
        print(f"### -Warning: Could not fetch schema. Proceeding. Error: {str(e)}")

    try:
        main_write_df.write \
            .option("truncate", "true") \
            .jdbc(
                url=jdbc_url,
                table=quoted_target_table,
                mode="overwrite", 
                properties=connection_properties
            )
        print("### -SUCCESS: Primary table loaded in strict sequential order.")

    except Exception as e:
        raise_custom_error("database_error", f"Primary write failed for {target_raw}: {str(e)[:100]}...", input_path)

    # ===============================================================================
    # --- DBWRITE 2: AUDIT TABLE (PARTIAL TRUNCATE) ---
    # ===============================================================================
    if audit_target_raw:
        quoted_audit_table = quote_table(audit_target_raw)
        print(f"### -Preparing audit write to {quoted_audit_table} with Bill Cycle: '{billcycle_val}'...")
        
        # Execute Partial Truncate (DELETE) via imported helper
        delete_query = f"DELETE FROM {quoted_audit_table} WHERE billcycle = '{billcycle_val}'"
        try:
            execute_postgres_query(glueContext, jdbc_url, connection_properties, delete_query)
        except Exception as e:
            raise_custom_error("audit_delete_error", f"Failed to delete old audit records: {str(e)}", input_path)

        # Construct Audit DataFrame
        audit_df = final_df.select(
            "*", 
            lit(billcycle_val).alias("billcycle"),
            lit(input_file_name).alias("filename"),
            uuidv7_udf().alias("sequencialid"),
            current_timestamp().alias("dateprocessed")
        ).withColumnRenamed("_temp_row_num", "rownumber")

        # Audit Schema Alignment
        try:
            audit_schema_df = spark.read.jdbc(url=jdbc_url, table=quoted_audit_table, properties=connection_properties)
            
            existing_cols_lower = [c.lower() for c in audit_df.columns]
            
            for a_col in audit_schema_df.columns:
                if a_col.lower() not in existing_cols_lower:
                    audit_df = audit_df.withColumn(a_col, lit(None).cast("string"))
                    
            audit_cols_to_select = [c for c in audit_schema_df.columns]
            audit_df = audit_df.select(*audit_cols_to_select)
            
        except Exception as e:
            print(f"### -Warning: Audit schema alignment skipped: {str(e)}")

        # Inject stringtype directly into the URL so the Postgres driver cannot ignore it
        separator = "&" if "?" in jdbc_url else "?"
        audit_jdbc_url = f"{jdbc_url}{separator}stringtype=unspecified"
        
        # Write via Append
        try:
            audit_df.write.jdbc(
                url=audit_jdbc_url, table=quoted_audit_table, mode="append", properties=connection_properties
            )
            print("### -SUCCESS: Audit table loaded via Append.")
        except Exception as e:
            raise_custom_error("audit_write_error", f"Audit write failed: {str(e)[:100]}...", input_path)
            
    # Uncache memory
    final_df.unpersist()